from pydantic import BaseModel
from model.job_channel_model import ShopModel


class SyncNotProductModel(BaseModel):
    description: str
    shop: ShopModel  # shop data as generated by firebase
    resolved: bool = False
    first_modified: str
    last_modified: str

    def to_json(self):
        load = {
            "description": self.description,
            "shop": self.shop.to_json(),
            "resolved": self.resolved,
            "firstModified": str(self.first_modified),
            "lastModified": str(self.last_modified)
        }
        return load
